name: Test

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']
    
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}
          args: --ignore-platform-reqs
      - uses: php-actions/phpunit@v4
        with:
          configuration: phpunit.xml
          php_version: ${{ matrix.php-version }}
          php_extensions: bcmath gmp xdebug
          version: 10.5.27
        env:
          XDEBUG_MODE: coverage
  phpcs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v5
        with:
          php_version: 8.1
          php_extensions: bcmath gmp xdebug
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar src --standard=ruleset.xml